# Generated by Django 5.1.8 on 2026-04-21 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_agricole', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recolte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produit', models.CharField(max_length=100)),
                ('quantite', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unite', models.CharField(default='kg', max_length=20)),
                ('date_reception', models.DateField(auto_now_add=True)),
                ('campagne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_agricole.campagne')),
                ('producteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_agricole.producteur')),
            ],
        ),
    ]
